import pygame
#Configuración de la pantalla
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

#HEROE
HERO_WIDTH = 80
HERO_HEIGHT = 120

HERO_HITBOX_WIDTH = 40
HERO_HITBOX_HEIGHT = 90

HERO_ATTACK_HITBOX_WIDTH = 70
HERO_ATTACK_HITBOX_HEIGHT = 40

HERO_HITBOX_OFFSET_X = 5

#ENEMIGOS

MAX_SKELETONS = 12
SKELETON_WIDTH = 80
SKELETON_HEIGHT = 105
SKELETON_HITBOX_WIDTH = 80
SKELETON_HITBOX_HEIGHT = 120

MAX_GHOSTS = 3
GHOST_WIDTH = 80
GHOST_HEIGHT = 105
GHOST_HITBOX_WIDTH = 80
GHOST_HITBOX_HEIGHT = 120

GHOST_SPAWN_HEIGHT_1 = SCREEN_HEIGHT - 210
GHOST_SPAWN_HEIGHT_2 = SCREEN_HEIGHT - 400
GHOST_SPAWN_HEIGHT_3 = SCREEN_HEIGHT - 590

SOUL_WIDTH = 15
SOUL_HEIGHT = 15

#EDIFICIOS

TOWER_WIDTH = SCREEN_WIDTH / 3
TOWER_HEIGHT = SCREEN_HEIGHT / 1.5

TOWER_HITBOX_WIDTH = 50
TOWER_HITBOX_HEIGHT = SCREEN_HEIGHT

#FPS
FPS = 60

#Velocidad
VELOCITY = 5

#Escala
SCALE = 2

#Events
LEVEL_UP_EVENT = pygame.USEREVENT+1
GAME_OVER_EVENT = pygame.USEREVENT+2
ATTACK_EVENT = pygame.USEREVENT+3
JUMP_EVENT = pygame.USEREVENT+4
SKELETON_DEATH_EVENT = pygame.USEREVENT+6


#Atura del suelo
GROUND_HEIGHT = SCREEN_HEIGHT - 32

#Altura rutas de vuelo
SKY_HEIGHT_1 = 0