import pygame
#Configuración de la pantalla
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

#HEROE
HERO_WIDTH = 80
HERO_HEIGHT = 120

HERO_HITBOX_WIDTH = 40
HERO_HITBOX_HEIGHT = 90

HERO_ATTACK_HITBOX_WIDTH = 70
HERO_ATTACK_HITBOX_HEIGHT = 40

#ENEMIGOS

MAX_ENEMIES = 10

SKELETON_WIDTH = 80
SKELETON_HEIGHT = 105

SKELETON_HITBOX_WIDTH = 80
SKELETON_HITBOX_HEIGHT = 120

SOUL_WIDTH = 15
SOUL_HEIGHT = 15

#EDIFICIOS

TOWER_WIDTH = SCREEN_WIDTH / 3
TOWER_HEIGHT = SCREEN_HEIGHT / 1.5

TOWER_HITBOX_WIDTH = 50
TOWER_HITBOX_HEIGHT = SCREEN_HEIGHT

#FPS
FPS = 60

#Velocidad
VELOCITY = 5

#Escala
SCALE = 2

#Events
LEVEL_UP_EVENT = pygame.USEREVENT+1
GAME_OVER_EVENT = pygame.USEREVENT+2